# Generated by Django 4.2 on 2023-05-13 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0010_rename_user_customer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='User',
            new_name='user',
        ),
    ]
